SELECT * FROM MatHang;
-- INDEX FOR MauSac column
SELECT * FROM MatHang 
WHERE MauSac = 'Xanh';

EXPLAIN SELECT * FROM MatHang WHERE MauSac = 'Xanh';

-- AUTO B-TREE
CREATE INDEX IDX_COLOR
ON MatHang(MauSac);

-- BEST PRACTICE
-- AUTO
-- 1. PRIMARY KEY - FILTER
-- 2. FOREIGN KEY - JOIN
-- MANUAL
-- 3. PERFORMANCE ISSUE WITH SEARCHING OR FILTER FREQUENT COLUMN IN WHERE CLAUSE >> INDEX
-- 